"use client";

/* eslint-disable @next/next/no-img-element -- foto autenticada fornecida pela API */

import { useEffect, useMemo, useState } from "react";
import { Check, Search } from "lucide-react";
import { requisitarApi, URL_API, type CatadorApi, type MaterialApi } from "@/app/dados/api";

type Referencia = { uuid: string; nome: string };

export function TelaPesagem() {
  const [etapa, setEtapa] = useState(0);
  const [catadores, setCatadores] = useState<CatadorApi[]>([]);
  const [materiais, setMateriais] = useState<MaterialApi[]>([]);
  const [pontos, setPontos] = useState<Referencia[]>([]);
  const [responsaveis, setResponsaveis] = useState<Referencia[]>([]);
  const [pontoUuid, setPontoUuid] = useState(""); const [responsavelUuid, setResponsavelUuid] = useState(""); const [responsavelOutro, setResponsavelOutro] = useState("");
  const [catadorUuid, setCatadorUuid] = useState(""); const [materialUuid, setMaterialUuid] = useState(""); const [peso, setPeso] = useState(""); const [observacao, setObservacao] = useState("");
  const [codigoRegistrado, setCodigoRegistrado] = useState(""); const [erro, setErro] = useState(""); const [salvando, setSalvando] = useState(false);
  useEffect(() => { void Promise.all([requisitarApi<{ dados: CatadorApi[] }>("/api/catadores?limite=100"), requisitarApi<{ dados: MaterialApi[] }>("/api/materiais"), requisitarApi<{ dados: Referencia[] }>("/api/pontos-apoio"), requisitarApi<{ dados: Referencia[] }>("/api/responsaveis-pesagem")]).then(([c, m, p, r]) => { setCatadores(c.dados.filter((item) => item.status === "ativo")); setMateriais(m.dados.filter((item) => item.status === "ativo")); setPontos(p.dados); setResponsaveis(r.dados); setPontoUuid(p.dados[0]?.uuid ?? ""); }).catch((falha) => setErro(falha instanceof Error ? falha.message : "Não foi possível carregar os dados.")); }, []);
  const catador = catadores.find((item) => item.uuid === catadorUuid); const material = materiais.find((item) => item.uuid === materialUuid);
  const pesoNumero = Number(peso.replace(",", ".")); const valor = useMemo(() => material && pesoNumero > 0 ? pesoNumero / Number(material.quantidade_referencia) * Number(material.valor_referencia) : 0, [material, pesoNumero]);
  const responsavelValido = responsavelUuid === "outro" ? responsavelOutro.trim().length >= 2 : Boolean(responsavelUuid);
  async function registrar() { if (!catador || !material || !pontoUuid || !responsavelValido || pesoNumero <= 0) return; setSalvando(true); setErro(""); try { const resposta = await requisitarApi<{ codigo: string }>("/api/pesagens", { method: "POST", body: JSON.stringify({ catadorUuid, pontoApoioUuid: pontoUuid, responsavelPesagemUuid: responsavelUuid === "outro" ? undefined : responsavelUuid, responsavelOutro: responsavelUuid === "outro" ? responsavelOutro.trim() : undefined, materialUuid, peso: pesoNumero, observacao: observacao.trim() || undefined }) }); setCodigoRegistrado(resposta.codigo); } catch (falha) { setErro(falha instanceof Error ? falha.message : "Não foi possível registrar a pesagem."); } finally { setSalvando(false); } }
  function reiniciar() { setEtapa(0); setCatadorUuid(""); setMaterialUuid(""); setPeso(""); setObservacao(""); setCodigoRegistrado(""); }
  if (codigoRegistrado) return <div className="painel sucesso-pesagem"><span><Check /></span><h2>Pesagem registrada com sucesso!</h2><p>O comprovante <strong>{codigoRegistrado}</strong> já está disponível nos relatórios.</p><div><button className="botao-secundario" onClick={reiniciar}>Registrar outra</button></div></div>;
  return <section className="pagina-interna pesagem"><div className="progresso-pesagem">{["Local e responsável", "Confirmar catador", "Material e peso", "Revisar"].map((item, i) => <div className={i === etapa ? "atual" : i < etapa ? "feito" : ""} key={item}><span>{i < etapa ? "✓" : i + 1}</span><small>{item}</small></div>)}</div><div className="painel formulario-pesagem">
    {etapa === 0 && <div className="animar-etapa"><span className="sobrelinha">ETAPA 1 DE 4</span><h2>Onde a pesagem está acontecendo?</h2><p>Selecione referências cadastradas no banco de dados.</p><div className="grade-formulario espacada"><label className="campo">Ponto de apoio<select value={pontoUuid} onChange={(e) => setPontoUuid(e.target.value)}><option value="">Selecionar</option>{pontos.map((item) => <option value={item.uuid} key={item.uuid}>{item.nome}</option>)}</select></label><label className="campo">Responsável pela pesagem<select value={responsavelUuid} onChange={(e) => setResponsavelUuid(e.target.value)}><option value="">Selecionar</option>{responsaveis.map((item) => <option value={item.uuid} key={item.uuid}>{item.nome}</option>)}<option value="outro">Outro</option></select></label>{responsavelUuid === "outro" && <label className="campo campo-largo">Nome do responsável<input value={responsavelOutro} onChange={(e) => setResponsavelOutro(e.target.value)} /></label>}</div></div>}
    {etapa === 1 && <div className="animar-etapa"><span className="sobrelinha">ETAPA 2 DE 4</span><h2>Quem está entregando o material?</h2><p>Busque o cadastro armazenado no PostgreSQL.</p><label className="campo-busca busca-grande"><Search /><select value={catadorUuid} onChange={(e) => setCatadorUuid(e.target.value)}><option value="">Buscar catador...</option>{catadores.map((item) => <option value={item.uuid} key={item.uuid}>{item.codigo} — {item.nome_completo}</option>)}</select></label>{catador && <div className="confirmar-catador">{catador.tem_foto ? <img className="foto-catador" src={`${URL_API}/api/catadores/${catador.uuid}/foto`} alt={`Foto de ${catador.nome_completo}`} /> : <div className="foto-catador">{catador.nome_completo.split(/\s+/).slice(0, 2).map((p) => p[0]).join("")}</div>}<div><span className="status ativo">● Cadastro ativo</span><h3>{catador.nome_completo}</h3><p><code>{catador.codigo}</code> · {catador.cooperativa ?? "Sem cooperativa"}</p><p>{catador.contatos[0]?.valor ?? "Contato não informado"}</p></div><div className="selo-confirmacao"><span><Check /></span><small>Confirme a identidade</small></div></div>}</div>}
    {etapa === 2 && <div className="animar-etapa"><span className="sobrelinha">ETAPA 3 DE 4</span><h2>Qual material foi pesado?</h2><p>Os valores abaixo são os configurados no banco.</p><div className="grade-materiais">{materiais.map((item) => <button type="button" className={materialUuid === item.uuid ? "cartao-material selecionado" : "cartao-material"} onClick={() => setMaterialUuid(item.uuid)} key={item.uuid}><span>{item.tipo_material.slice(0, 2).toUpperCase()}</span><strong>{item.nome}</strong><small>{Number(item.valor_referencia).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })} / {Number(item.quantidade_referencia)} {item.unidade}</small>{materialUuid === item.uuid && <i>✓</i>}</button>)}</div><div className="grade-formulario espacada"><label className="campo campo-peso">Peso do material<div><input value={peso} onChange={(e) => setPeso(e.target.value)} inputMode="decimal" placeholder="0,00" /><span>{material?.unidade.toUpperCase() ?? "KG"}</span></div></label><label className="campo campo-largo">Observação <small>Opcional</small><textarea value={observacao} onChange={(e) => setObservacao(e.target.value)} /></label></div></div>}
    {etapa === 3 && <div className="animar-etapa"><span className="sobrelinha">ETAPA 4 DE 4</span><h2>Revise antes de registrar</h2><div className="resumo-pesagem"><div className="linha-resumo"><span>Catador</span><strong>{catador?.nome_completo}</strong></div><div className="linha-resumo"><span>Material</span><strong>{material?.nome}</strong></div><div className="linha-resumo"><span>Peso</span><strong>{pesoNumero.toLocaleString("pt-BR")} {material?.unidade}</strong></div><div className="linha-resumo"><span>Valor de referência</span><strong>{Number(material?.valor_referencia ?? 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })} / {Number(material?.quantidade_referencia ?? 1)} {material?.unidade}</strong></div><div className="total-pesagem"><span>Valor total calculado</span><strong>{valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></div></div></div>}
    {erro && <p className="mensagem-erro" role="alert">{erro}</p>}<footer className="rodape-fluxo"><button className="botao-secundario" disabled={etapa === 0} onClick={() => setEtapa((v) => Math.max(0, v - 1))}>← Voltar</button><button className="botao-primario" disabled={salvando || (etapa === 0 && (!pontoUuid || !responsavelValido)) || (etapa === 1 && !catador) || (etapa === 2 && (!material || pesoNumero <= 0))} onClick={etapa === 3 ? () => void registrar() : () => setEtapa((v) => Math.min(3, v + 1))}>{salvando ? "Registrando..." : etapa === 3 ? "Confirmar e registrar" : "Continuar →"}</button></footer>
  </div></section>;
}
