"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Search } from "lucide-react";
import { requisitarApi } from "@/app/dados/api";

type PesagemApi = { uuid: string; codigo: string; criado_em: string; peso_total: number; valor_total: number; catador: string; material: string; ponto_apoio: string; responsavel: string };

export function TelaRelatorios() {
  const [pesagens, setPesagens] = useState<PesagemApi[]>([]); const [busca, setBusca] = useState(""); const [inicio, setInicio] = useState(""); const [fim, setFim] = useState(""); const [erro, setErro] = useState("");
  const carregar = useCallback(async () => { try { const consulta = new URLSearchParams({ limite: "200" }); if (inicio) consulta.set("inicio", inicio); if (fim) consulta.set("fim", fim); const dados = await requisitarApi<{ dados: PesagemApi[] }>(`/api/relatorios/pesagens?${consulta}`); setPesagens(dados.dados); setErro(""); } catch (falha) { setErro(falha instanceof Error ? falha.message : "Não foi possível carregar os relatórios."); } }, [fim, inicio]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void carregar(); }, [carregar]);
  const filtradas = useMemo(() => pesagens.filter((item) => `${item.catador} ${item.codigo} ${item.material}`.toLowerCase().includes(busca.toLowerCase())), [busca, pesagens]);
  const totais = useMemo(() => filtradas.reduce((acc, item) => ({ peso: acc.peso + Number(item.peso_total), valor: acc.valor + Number(item.valor_total) }), { peso: 0, valor: 0 }), [filtradas]);
  function exportar() { const linhas = [["Código", "Data", "Catador", "Material", "Ponto de apoio", "Responsável", "Peso", "Valor"], ...filtradas.map((p) => [p.codigo, new Date(p.criado_em).toLocaleString("pt-BR"), p.catador, p.material, p.ponto_apoio, p.responsavel, String(p.peso_total), String(p.valor_total)])]; const csv = linhas.map((linha) => linha.map((campo) => `"${String(campo).replaceAll('"', '""')}"`).join(";")).join("\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "relatorio-pesagens.csv"; link.click(); URL.revokeObjectURL(url); }
  return <section className="pagina-interna"><div className="resumo-pagina"><div><h2>Produção e pagamentos</h2><p>Dados completos das pesagens registradas.</p></div><button className="botao-secundario" onClick={exportar} disabled={filtradas.length === 0}><Download /> Exportar relatório</button></div>{erro && <p className="mensagem-erro" role="alert">{erro}</p>}<div className="grade-resumo-relatorio"><article><span>KG</span><div><small>Peso no período</small><strong>{totais.peso.toLocaleString("pt-BR")} kg</strong></div></article><article><span>R$</span><div><small>Valor gerado</small><strong>{totais.valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></div></article><article><span>№</span><div><small>Pesagens</small><strong>{filtradas.length} registros</strong></div></article></div><div className="barra-ferramentas"><label className="campo-busca"><Search /><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar catador, material ou código..." /></label><input className="entrada-filtro" type="date" value={inicio} onChange={(e) => setInicio(e.target.value)} aria-label="Data inicial" /><input className="entrada-filtro" type="date" value={fim} onChange={(e) => setFim(e.target.value)} aria-label="Data final" /></div><div className="tabela-responsiva"><table><thead><tr><th>Registro</th><th>Catador</th><th>Material</th><th>Local</th><th>Peso</th><th>Valor</th></tr></thead><tbody>{filtradas.map((p) => <tr key={p.uuid}><td><code>{p.codigo}</code><small className="texto-bloco">{new Date(p.criado_em).toLocaleString("pt-BR")}</small></td><td><strong>{p.catador}</strong><small className="texto-bloco">Por {p.responsavel}</small></td><td>{p.material}</td><td>{p.ponto_apoio}</td><td><strong>{Number(p.peso_total).toLocaleString("pt-BR")} kg</strong></td><td><strong className="valor-verde">{Number(p.valor_total).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></td></tr>)}</tbody></table>{filtradas.length === 0 && <p className="estado-vazio">Nenhuma pesagem encontrada.</p>}</div></section>;
}
