"use client";

import { useMemo, useState } from "react";
import { catadores, materiais } from "@/app/dados/demonstracao";

export function TelaPesagem() {
  const [etapa, setEtapa] = useState(0);
  const [catadorUuid, setCatadorUuid] = useState("");
  const [materialUuid, setMaterialUuid] = useState("");
  const [peso, setPeso] = useState("");
  const [registrado, setRegistrado] = useState(false);
  const catador = catadores.find((item)=>item.uuid===catadorUuid);
  const material = materiais.find((item)=>item.uuid===materialUuid);
  const valor = useMemo(()=>material && Number(peso) ? Number(peso) / material.quantidadeReferencia * material.valorReferencia : 0,[material,peso]);

  if (registrado) return <div className="painel sucesso-pesagem"><span>✓</span><h2>Pesagem registrada com sucesso!</h2><p>O comprovante <strong>PES-0187</strong> está disponível nos relatórios.</p><div><button className="botao-secundario" onClick={()=>{setRegistrado(false);setEtapa(0);setCatadorUuid("");setMaterialUuid("");setPeso("")}}>Registrar outra</button><button className="botao-primario">Imprimir comprovante</button></div></div>;

  return <section className="pagina-interna pesagem">
    <div className="progresso-pesagem">{["Local e responsável","Confirmar catador","Material e peso","Revisar"].map((item,i)=><div className={i===etapa?"atual":i<etapa?"feito":""} key={item}><span>{i<etapa?"✓":i+1}</span><small>{item}</small></div>)}</div>
    <div className="painel formulario-pesagem">
      {etapa===0&&<div className="animar-etapa"><span className="sobrelinha">ETAPA 1 DE 4</span><h2>Onde a pesagem está acontecendo?</h2><p>Essas informações ajudam a organizar a produção por ponto de apoio.</p><div className="grade-formulario espacada"><label className="campo">Ponto de apoio<select defaultValue="Praça da Estação"><option>Praça da Estação</option><option>Viaduto Santa Tereza</option><option>Parque Municipal</option></select></label><label className="campo">Responsável pela pesagem<select defaultValue=""><option value="">Selecionar responsável</option><option>João da Silva</option><option>Maria Aparecida</option><option>Carlos Eduardo</option><option>Outro</option></select></label><label className="campo campo-largo">Nome do responsável <small>Preencha apenas se marcou “Outro”</small><input placeholder="Digite o nome completo" /></label></div></div>}
      {etapa===1&&<div className="animar-etapa"><span className="sobrelinha">ETAPA 2 DE 4</span><h2>Quem está entregando o material?</h2><p>Busque por código ou nome e confirme a identidade pela foto.</p><label className="campo-busca busca-grande"><span>⌕</span><select value={catadorUuid} onChange={(e)=>setCatadorUuid(e.target.value)}><option value="">Buscar catador...</option>{catadores.map(c=><option value={c.uuid} key={c.uuid}>{c.codigo} — {c.nomeCompleto}</option>)}</select></label>{catador&&<div className="confirmar-catador"><div className="foto-catador">{catador.iniciais}</div><div><span className="status ativo">● Cadastro ativo</span><h3>{catador.nomeCompleto}</h3><p><code>{catador.codigo}</code> · {catador.cooperativa}</p><p>{catador.telefone}</p></div><div className="selo-confirmacao"><span>✓</span><small>Confirme se a foto<br/>corresponde à pessoa</small></div></div>}</div>}
      {etapa===2&&<div className="animar-etapa"><span className="sobrelinha">ETAPA 3 DE 4</span><h2>Qual material foi pesado?</h2><p>Selecione o material e informe o peso conferido na balança.</p><div className="grade-materiais">{materiais.filter(m=>m.ativo).map(m=><button className={materialUuid===m.uuid?"cartao-material selecionado":"cartao-material"} onClick={()=>setMaterialUuid(m.uuid)} key={m.uuid}><span style={{background:m.cor}}>{m.tipo.slice(0,2).toUpperCase()}</span><strong>{m.nome}</strong><small>R$ {m.valorReferencia.toFixed(2).replace(".",",")} / {m.quantidadeReferencia} {m.unidade}</small>{materialUuid===m.uuid&&<i>✓</i>}</button>)}</div><div className="grade-formulario espacada"><label className="campo campo-peso">Peso do material <div><input value={peso} onChange={(e)=>setPeso(e.target.value)} inputMode="decimal" placeholder="0,00"/><span>KG</span></div></label><label className="campo campo-largo">Observação <small>Opcional</small><textarea placeholder="Ex.: material úmido, embalagem separada..." /></label></div></div>}
      {etapa===3&&<div className="animar-etapa"><span className="sobrelinha">ETAPA 4 DE 4</span><h2>Revise antes de registrar</h2><p>Confira os dados com o catador para evitar divergências.</p><div className="resumo-pesagem"><div className="linha-resumo"><span>Catador</span><strong>{catador?.nomeCompleto ?? "Não selecionado"}</strong></div><div className="linha-resumo"><span>Material</span><strong>{material?.nome ?? "Não selecionado"}</strong></div><div className="linha-resumo"><span>Peso registrado</span><strong>{Number(peso).toLocaleString("pt-BR",{minimumFractionDigits:2})} kg</strong></div><div className="linha-resumo"><span>Valor por referência</span><strong>R$ {material?.valorReferencia.toFixed(2).replace(".",",") ?? "0,00"} / {material?.quantidadeReferencia ?? 1} kg</strong></div><div className="total-pesagem"><span>Valor total da pesagem</span><strong>{valor.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div></div><label className="confirmacao"><input type="checkbox" /> O catador conferiu e está de acordo com os dados da pesagem.</label></div>}
      <footer className="rodape-fluxo"><button className="botao-secundario" disabled={etapa===0} onClick={()=>setEtapa(v=>Math.max(0,v-1))}>← Voltar</button><button className="botao-primario" disabled={(etapa===1&&!catador)||(etapa===2&&(!material||!peso))} onClick={etapa===3?()=>setRegistrado(true):()=>setEtapa(v=>Math.min(3,v+1))}>{etapa===3?"Confirmar e registrar":"Continuar →"}</button></footer>
    </div>
  </section>;
}
