"use client";

import { useState } from "react";
import { catadores } from "@/app/dados/demonstracao";

const etapas = ["Identificação", "Contato e endereço", "Pagamento", "Foto e revisão"];

export function TelaCatadores() {
  const [busca, setBusca] = useState("");
  const [cadastroAberto, setCadastroAberto] = useState(false);
  const filtrados = catadores.filter((item) => `${item.nomeCompleto} ${item.apelido ?? ""} ${item.codigo}`.toLowerCase().includes(busca.toLowerCase()));

  return <section className="pagina-interna">
    <div className="resumo-pagina"><div><h2>48 catadores cadastrados</h2><p>Gerencie dados pessoais, contatos e vínculos com cooperativas.</p></div><button className="botao-primario" onClick={() => setCadastroAberto(true)}>＋ Cadastrar catador</button></div>
    <div className="barra-ferramentas"><label className="campo-busca"><span>⌕</span><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar por nome, apelido ou código..." /></label><button className="botao-secundario">Filtros</button></div>
    <div className="tabela-responsiva"><table><thead><tr><th>Catador</th><th>Código</th><th>Cooperativa</th><th>Contato</th><th>Coletado</th><th>Status</th><th aria-label="Ações" /></tr></thead><tbody>{filtrados.map((catador)=><tr key={catador.uuid}><td><div className="pessoa"><span>{catador.iniciais}</span><div><strong>{catador.nomeCompleto}</strong><small>{catador.apelido ? `Prefere: ${catador.apelido}` : "Nome completo"}</small></div></div></td><td><code>{catador.codigo}</code></td><td>{catador.cooperativa}</td><td>{catador.telefone}</td><td><strong>{catador.totalQuilos.toLocaleString("pt-BR")} kg</strong></td><td><span className="status ativo">● {catador.status}</span></td><td><button className="menu-acoes">•••</button></td></tr>)}</tbody></table></div>
    {cadastroAberto && <CadastroCatador onFechar={() => setCadastroAberto(false)} />}
  </section>;
}

function CadastroCatador({ onFechar }: { onFechar: () => void }) {
  const [etapa, setEtapa] = useState(0);
  const [endereco, setEndereco] = useState(false);
  const [pagamento, setPagamento] = useState(false);
  const [terceiro, setTerceiro] = useState(false);
  const [contatos, setContatos] = useState([0]);
  const [concluido, setConcluido] = useState(false);

  if (concluido) return <div className="sobreposicao" role="dialog" aria-modal="true"><div className="modal cadastro"><div className="sucesso"><span>✓</span><h2>Cadastro concluído!</h2><p>O catador foi registrado com o código <strong>CAT-0049</strong>.</p><button className="botao-primario" onClick={onFechar}>Voltar para catadores</button></div></div></div>;

  return <div className="sobreposicao" role="dialog" aria-modal="true" aria-labelledby="titulo-cadastro">
    <div className="modal cadastro">
      <header className="cabecalho-modal"><div><span>NOVO CADASTRO</span><h2 id="titulo-cadastro">Cadastrar catador</h2><p>Preencha no ritmo da pessoa. Campos não essenciais são opcionais.</p></div><button onClick={onFechar} aria-label="Fechar">×</button></header>
      <div className="etapas">{etapas.map((item, indice)=><div className={indice === etapa ? "etapa atual" : indice < etapa ? "etapa concluida" : "etapa"} key={item}><span>{indice < etapa ? "✓" : indice + 1}</span><small>{item}</small></div>)}</div>
      <form className="formulario" onSubmit={(e)=>e.preventDefault()}>
        {etapa === 0 && <div className="animar-etapa"><h3>Como a pessoa deseja ser identificada?</h3><div className="grade-formulario"><label className="campo campo-largo">Nome completo <input placeholder="Digite o nome completo" autoFocus /></label><label className="campo">Apelido <small>Opcional</small><input placeholder="Como deseja ser chamada?" /></label><label className="campo">Código <input value="Gerado automaticamente" disabled /></label><label className="campo">Gênero <small>Opcional</small><select defaultValue=""><option value="">Selecionar</option><option>Feminino</option><option>Masculino</option><option>Não binário</option><option>Prefere não informar</option><option>Outro</option></select></label><label className="campo">Raça / Cor <small>Opcional</small><select defaultValue=""><option value="">Selecionar</option><option>Branca</option><option>Preta</option><option>Parda</option><option>Amarela</option><option>Indígena</option><option>Prefere não informar</option></select></label><label className="campo">Data de nascimento <small>Opcional</small><input type="date" /></label><label className="campo">CPF <small>Opcional</small><input inputMode="numeric" placeholder="000.000.000-00" /></label><label className="campo campo-largo">Cooperativa / Associação <select defaultValue=""><option value="">Selecionar vínculo</option>{["Coopesol Leste","Coopesol Barreiro","Asmare","Copemar","Copemarc","Catunidos","Assoce Recicle","Outras"].map(i=><option key={i}>{i}</option>)}</select></label></div></div>}
        {etapa === 1 && <div className="animar-etapa"><h3>Como podemos entrar em contato?</h3>{contatos.map((chave, indice)=><div className="grupo-repetivel" key={chave}><label className="campo">Tipo de contato<select><option>Celular</option><option>Telefone</option><option>WhatsApp</option><option>Recado</option></select></label><label className="campo">Número<input inputMode="tel" placeholder="(31) 99999-9999" /></label>{indice > 0 && <button onClick={()=>setContatos((lista)=>lista.filter((_,i)=>i!==indice))} type="button" aria-label="Remover contato">×</button>}</div>)}<button className="botao-texto" type="button" onClick={()=>setContatos((lista)=>[...lista,Date.now()])}>＋ Adicionar outro contato</button><div className="bloco-opcional"><label className="interruptor"><input type="checkbox" checked={endereco} onChange={(e)=>setEndereco(e.target.checked)} /><span /> <div><strong>Preencher endereço</strong><small>Opcional — ative apenas se a pessoa desejar informar</small></div></label>{endereco && <div className="grade-formulario animar-etapa"><label className="campo">CEP<input placeholder="00000-000" inputMode="numeric" /><small className="dica">O endereço será preenchido automaticamente</small></label><label className="campo campo-largo">Logradouro<input placeholder="Rua, avenida ou praça" /></label><label className="campo">Número<input placeholder="Número" /></label><label className="campo">Complemento <small>Opcional</small><input placeholder="Casa, lote, referência" /></label><label className="campo">Bairro<input /></label><label className="campo">Cidade<input defaultValue="Belo Horizonte" /></label><label className="campo">Estado<input defaultValue="MG" /></label></div>}</div></div>}
        {etapa === 2 && <div className="animar-etapa"><h3>Dados para recebimento</h3><div className="bloco-opcional"><label className="interruptor"><input type="checkbox" checked={pagamento} onChange={(e)=>setPagamento(e.target.checked)} /><span/><div><strong>Informar Pix ou conta bancária</strong><small>Opcional — pode ser preenchido depois</small></div></label>{pagamento && <div className="animar-etapa"><div className="seletor-segmentado"><button className="selecionado" type="button">Pix</button><button type="button">Conta bancária</button></div><div className="grade-formulario"><label className="campo">Tipo da chave<select><option>CPF</option><option>Celular</option><option>E-mail</option><option>Chave aleatória</option></select></label><label className="campo campo-largo">Chave Pix<input placeholder="Digite a chave" /></label></div><label className="interruptor compacto"><input type="checkbox" checked={terceiro} onChange={(e)=>setTerceiro(e.target.checked)} /><span/><div><strong>O recebimento será feito por terceiro</strong></div></label>{terceiro && <div className="grade-formulario"><label className="campo">Nome do titular<input /></label><label className="campo">CPF do titular<input placeholder="000.000.000-00" /></label><label className="campo campo-largo">Relação com o catador <small>Opcional</small><input placeholder="Ex.: familiar, pessoa de confiança" /></label></div>}</div>}</div></div>}
        {etapa === 3 && <div className="animar-etapa"><h3>Foto e revisão</h3><div className="area-foto"><div className="moldura-rosto"><span>♙</span></div><div><strong>Fotografe o rosto do catador</strong><p>Peça autorização e mantenha o rosto centralizado em local bem iluminado.</p><button type="button" className="botao-secundario">◎ Abrir câmera</button></div></div><div className="aviso-privacidade"><span>🔒</span><p>A foto será armazenada com acesso restrito e usada somente para confirmação durante as pesagens.</p></div><label className="confirmacao"><input type="checkbox" /> Confirmo que revisei as informações e obtive autorização para registrar a foto.</label></div>}
      </form>
      <footer className="rodape-modal"><button type="button" className="botao-secundario" onClick={etapa === 0 ? onFechar : ()=>setEtapa((v)=>v-1)}>{etapa === 0 ? "Cancelar" : "← Voltar"}</button><span>Etapa {etapa + 1} de {etapas.length}</span><button type="button" className="botao-primario" onClick={etapa === etapas.length-1 ? ()=>setConcluido(true) : ()=>setEtapa((v)=>v+1)}>{etapa === etapas.length-1 ? "Concluir cadastro" : "Continuar →"}</button></footer>
    </div>
  </div>;
}
